name: default

on:
  push:
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}

jobs:
  integration:
    runs-on: ubuntu-latest

    container: "node:18"

    steps:
      - uses: actions/checkout@v2

      - name: Audit
        run: cd price-server; npm audit

  delivery:
    runs-on: ubuntu-latest
    needs: integration
    permissions:
      contents: read
      packages: write

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push docker image for price-server to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./price-server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oracle-price-server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oracle-price-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
    
      - name: Build, tag, and push docker image for feeder to GHCR
        uses: docker/build-push-action@v2
        with:
          context: ./feeder
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oracle-feeder:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/oracle-feeder:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
